"use client";

import { useState, useEffect, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { ArrowLeft, Download, FileText, Loader2, AlertTriangle, CheckCircle2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { generateReportPdf } from "@/lib/report-utils";

function AdminReportViewer() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const id = searchParams.get('id');
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    const fetchReport = async () => {
      try {
        const res = await fetch(`/api/admin/reports/${id}`);
        const data = await res.json();
        if (data.report) setReport(data.report);
      } catch (err) {
        console.error("Failed to fetch report", err);
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, [id]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh]">
        <Loader2 className="h-8 w-8 animate-spin text-slate-400 mb-4" />
        <p className="text-slate-500 font-medium">Retrieving secure report data...</p>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center py-20">
        <h2 className="text-xl font-bold text-slate-900">Report Not Found</h2>
        <Button onClick={() => router.back()} className="mt-4">Go Back</Button>
      </div>
    );
  }

  const { result, inputData } = report;
  const isEmergency = result.risk_level === "Emergency";
  const isHigh = result.risk_level === "High";
  const isModerate = result.risk_level === "Moderate";
  
  const textColor = isEmergency ? 'text-red-600' : isHigh ? 'text-orange-600' : isModerate ? 'text-amber-600' : 'text-emerald-600';
  const borderColor = isEmergency ? 'border-red-200' : isHigh ? 'border-orange-200' : isModerate ? 'border-amber-200' : 'border-emerald-200';
  const bgColor = isEmergency ? 'bg-red-50' : isHigh ? 'bg-orange-50' : isModerate ? 'bg-amber-50' : 'bg-emerald-50';

  return (
    <div className="max-w-4xl mx-auto py-8 px-4">
      <div className="flex items-center justify-between mb-6">
        <Button variant="ghost" onClick={() => router.back()} className="text-slate-500 hover:text-slate-900">
          <ArrowLeft className="h-4 w-4 mr-2" /> Back to All Reports
        </Button>
        <Button 
          className="bg-slate-900 hover:bg-slate-800 text-white rounded-xl shadow-md"
          onClick={() => {
            generateReportPdf({
              patientName: report.patientName,
              patientRef: report.patientRef,
              date: report.createdAt,
              riskLevel: report.riskLevel,
              summary: result.summary,
              urgency: result.urgency,
              confidenceScore: result.confidence_score,
              keyRiskFactors: result.key_risk_factors,
              possibleConditions: result.possible_conditions,
              recommendation: result.recommendation,
              inputData: inputData
            });
          }}
        >
          <Download className="h-4 w-4 mr-2" /> Download Official PDF
        </Button>
      </div>

      <Card className="shadow-2xl border-0 overflow-hidden bg-white rounded-3xl">
        <div className={`h-2 w-full ${isEmergency ? 'bg-red-600' : isHigh ? 'bg-orange-500' : isModerate ? 'bg-amber-500' : 'bg-emerald-500'}`}></div>
        <CardHeader className="text-center pb-6 border-b border-slate-50">
           <div className="flex items-center justify-between mb-4">
              <div className="text-left">
                 <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Report ID</p>
                 <p className="text-sm font-bold text-slate-900">{report.patientRef}</p>
              </div>
              <div className="text-right">
                 <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Generated By</p>
                 <p className="text-sm font-bold text-slate-900">{report.user?.name}</p>
              </div>
           </div>
          <div className="flex justify-center mb-4">
            {isEmergency || isHigh ? (
              <AlertTriangle className={`h-16 w-16 ${textColor}`} />
            ) : (
              <CheckCircle2 className={`h-16 w-16 ${textColor}`} />
            )}
          </div>
          <CardTitle className="text-3xl font-serif text-slate-900 uppercase tracking-tight">Diagnostic Analysis</CardTitle>
          <div className={`mt-4 inline-block px-6 py-2 rounded-full border-2 text-sm font-black uppercase tracking-[0.2em] ${textColor} ${borderColor} ${bgColor}`}>
            {result.risk_level} RISK DETECTED
          </div>
        </CardHeader>

        <CardContent className="space-y-10 px-8 pt-8">
          <div className="p-6 rounded-3xl bg-slate-50 border border-slate-100 text-slate-600 text-sm leading-relaxed">
            <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-2">Clinical Executive Summary</h4>
            {result.summary}
          </div>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-orange-500"></span>
                Primary Risk Factors
              </h4>
              <ul className="space-y-2">
                {result.key_risk_factors.map((factor: string, i: number) => (
                  <li key={i} className="flex items-start text-sm text-slate-700 font-medium bg-slate-50 p-3 rounded-xl border border-slate-100">
                    {factor}
                  </li>
                ))}
              </ul>
            </div>
            <div className="space-y-4">
              <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-blue-500"></span>
                Differential Diagnosis
              </h4>
              <ul className="space-y-2">
                {result.possible_conditions.map((cond: string, i: number) => (
                  <li key={i} className="flex items-start text-sm text-slate-700 font-medium bg-slate-50 p-3 rounded-xl border border-slate-100">
                    {cond}
                  </li>
                ))}
              </ul>
            </div>
          </div>
          
          <div className={`p-8 rounded-3xl border-2 ${borderColor} ${bgColor}`}>
            <h4 className={`font-black text-xs uppercase tracking-widest mb-4 ${textColor}`}>Cardiology Recommendation</h4>
            <p className="text-base font-bold text-slate-900 leading-relaxed">{result.recommendation}</p>
          </div>

          <div className="space-y-6 pt-6 border-t border-slate-100">
            <h3 className="text-xl font-serif font-bold text-slate-900 flex items-center gap-2">
            <FileText className="h-5 w-5 text-slate-400" />
              Patient Health Profile
            </h3>
            
            <div className="grid md:grid-cols-2 gap-x-8 gap-y-6">
              <div className="space-y-4">
                <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest">Biometrics</h4>
                <div className="grid grid-cols-2 gap-4">
                   <DataField label="Patient Name" value={report.patientName} />
                   <DataField label="Age / Gender" value={`${inputData.age} / ${inputData.gender}`} />
                   <DataField label="Height" value={`${inputData.height} cm`} />
                   <DataField label="Weight" value={`${inputData.weight} kg`} />
                </div>
              </div>

              <div className="space-y-4">
                <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest">Vital Signs</h4>
                <div className="grid grid-cols-2 gap-4">
                   <DataField label="BP" value={`${inputData.bp_sys}/${inputData.bp_dia}`} />
                   <DataField label="Heart Rate" value={`${inputData.heart_rate} bpm`} />
                   <DataField label="Blood Sugar" value={`${inputData.blood_sugar} mg/dL`} />
                   <DataField label="SpO2" value={inputData.spo2 ? `${inputData.spo2}%` : "N/A"} />
                </div>
              </div>
            </div>
          </div>
        </CardContent>

        <CardFooter className="bg-slate-50/50 border-t border-slate-100 p-8 flex justify-center">
          <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest text-center max-w-md">
            Internal Administrative View. This report is stored for auditing and clinical follow-up.
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}

function DataField({ label, value }: { label: string, value: any }) {
  return (
    <div className="flex flex-col gap-0.5">
       <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">{label}</span>
       <span className="text-sm font-bold text-slate-900">{value || "N/A"}</span>
    </div>
  );
}

export default function AdminViewReportPage() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center min-h-screen text-slate-400"><Loader2 className="h-8 w-8 animate-spin" /></div>}>
      <AdminReportViewer />
    </Suspense>
  );
}
